#!/usr/bin/env python3
"""Generate docs/API_REFERENCE.md from the public functions and classes of the Sideband modules.

Run: python scripts/generate_api_reference.py [--check]
--check exits nonzero when the committed file differs from the generated text.
"""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]  # repository root: flat modules live there
sys.path.insert(0, str(ROOT))

import argparse
import importlib
import inspect
import os

for name in ("OMP_NUM_THREADS", "OPENBLAS_NUM_THREADS", "VECLIB_MAXIMUM_THREADS"):
    os.environ.setdefault(name, "1")
os.environ.setdefault("MPLBACKEND", "Agg")

MODULES = ("sideband", "sbfit", "sb_run", "sb_analysis", "sb_bootstrap", "sb_checkpoint", "sb_diagnostics",
           "sb_parallel", "sb_report", "sb_design", "sb_compare", "sb_workflow", "sb_import", "sb_server",
           "sb_cli", "validate_uncertainty")
OUTPUT = ROOT / "docs" / "API_REFERENCE.md"


def _summary(obj):
    # Raw docstrings only: inherited documentation would misdescribe overrides.
    doc = inspect.cleandoc(obj.__doc__) if getattr(obj, "__doc__", None) else ""
    paragraph = doc.split("\n\n", 1)[0].strip()
    return " ".join(paragraph.split()) or "(no docstring)"


def _signature(obj):
    try:
        return str(inspect.signature(obj))
    except (TypeError, ValueError):
        return "(...)"


def render():
    lines = ["# SBONEST API reference", "",
             "Generated by `generate_api_reference.py` from the public names of the Sideband modules "
             "(functions and classes without a leading underscore, defined in the module). Regenerate after "
             "changing a public signature; CI compares this file with the generated text.", ""]
    sys.path.insert(0, str(ROOT))
    for name in MODULES:
        module = importlib.import_module(name)
        lines.extend([f"## `{name}.py`", "", _summary(module), ""])
        members = [(n, obj) for n, obj in vars(module).items()
                   if not n.startswith("_") and getattr(obj, "__module__", None) == name
                   and (inspect.isfunction(obj) or inspect.isclass(obj))]
        for member_name, obj in sorted(members, key=lambda item: (not inspect.isclass(item[1]), item[0])):
            if inspect.isclass(obj):
                lines.append(f"- **class `{member_name}`** — {_summary(obj)}")
                for method_name, method in sorted(vars(obj).items()):
                    if method_name.startswith("_") and method_name != "__init__":
                        continue
                    if inspect.isfunction(method):
                        lines.append(f"  - `{method_name}{_signature(method)}` — {_summary(method)}")
            else:
                lines.append(f"- `{member_name}{_signature(obj)}` — {_summary(obj)}")
        lines.append("")
    return "\n".join(lines).rstrip("\n") + "\n"


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="Compare with the committed file instead of writing")
    args = parser.parse_args(argv)
    text = render()
    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current != text:
            print(f"{OUTPUT.relative_to(ROOT)} is out of date; run python scripts/generate_api_reference.py", file=sys.stderr)
            return 1
        print(f"{OUTPUT.relative_to(ROOT)} is up to date")
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)} ({text.count(chr(10))} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
